require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'Gemfile'
    - 'config.ru'
    - 'Rakefile'
    - 'bin/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'frontend/**/*'

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/GuardClause:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

IfUnlessModifier:
  Enabled: false

