services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: 'Asia/Tokyo'
      RAILS_ENV: development
      DATABASE_NAME: db/development.sqlite3
      DATABASE_NAME_TEST: db/test.sqlite3
    volumes:
      - .:/webapp:cached
      - tmp-data:/webapp/tmp
      - log-data:/webapp/log
    tty: true
    stdin_open: true
    depends_on:
      - frontend
    command: >-
      bash -c "rm -f tmp/pids/server.pid &&
      bundle config set --local path 'vendor/bundle' &&
      bundle config set clean 'true' &&
      bundle install &&
      bin/rails db:create db:migrate &&
      bin/rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    dns:
      - 9.9.9.9
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /webapp/frontend
    volumes:
      - .:/webapp:cached
      - ./frontend:/webapp/frontend
    tty: true
    stdin_open: true
    environment:
      TZ: 'Asia/Tokyo'
      NODE_ENV: development
    command: >-
      bash -c "npm install &&
      npm run build"
    ports:
      - "4200:4200"

volumes:
  tmp-data:
  log-data:
