apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  # ingress 経由なのでクラスタ内に閉じておく
  # type: ClusterIP
  type: NodePort
  selector:
    app: webapp-on-k8s
    # server: web
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp-on-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-on-k8s
      # server: web
  template:
    metadata:
      labels:
        app: webapp-on-k8s
        server: web
    spec:
      volumes:
        - name: sockets
          emptyDir: {}
      containers:
        - name: webapp-on-k8s
          image: webapp:0.0.1
          # デフォルトで pull しにいってコケるので Never させないようにする(webapp:latest などの場合)
          imagePullPolicy: Never
          command:
            - /bin/bash
          args:
            - -c
            - bin/rails db:migrate && bin/rails db:seed && bin/rails server -b 0.0.0.0 && cd frontend && npm run build
          ports:
            # service から受けるポート
            - name: http
              containerPort: 3000
