---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/baseball_players":
    get:
      summary: GET baseball_players
      responses:
        '200':
          description: Success
servers:
- url: http://localhost:3000
