---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/baseball_players":
    get:
      summary: GET baseball_players
      responses:
        '200':
          description: baseball_players
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  example:
                    id: 1
                    name: 大谷 翔平
                    team: ロサンゼルス・ドジャース
                    position: ２番DH
                    hometown: 岩手県
servers:
- url: http://localhost:3000
